language: csharp
solution: Unosquare.Tubular.Lib.sln
install:
  - nuget restore Unosquare.Tubular.Lib.sln
  - npm install
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm start > /dev/null &
  - npm run update-webdriver
  - sleep 1 # give server time to start
script:
  - xbuild /p:Configuration=Release Unosquare.Tubular.Lib.sln
  - npm run-script test-travis
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - node_modules/.bin/protractor e2e-tests/protractor.conf.js --browser=firefox
