language: csharp
solution: Unosquare.Tubular.Lib.sln
-addons:
 -  sauce_connect:
 -    username: "geoperez"
 -    access_key: "dd986cd7-696b-433a-941e-3820d83aa09a"
install:
  - nuget restore Unosquare.Tubular.Lib.sln
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install
env:
  - TRAVIS_NODE_VERSION="4"
before_script:
  - touch /home/travis/build/unosquare/tubular/Unosquare.Tubular/Javascript/tubular-bundle.js
  - touch /home/travis/build/unosquare/tubular/Unosquare.Tubular/Javascript/tubular-bundle.min.js
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm start > /dev/null &
  - sleep 1 # give server time to start
script:
  - xbuild /p:Configuration=Release Unosquare.Tubular.Lib.sln
  - ./node_modules/protractor/bin/webdriver-manager update
  - grunt test