language: csharp
node_js:
  - "0.12"
solution: Unosquare.Tubular.Lib.sln
install:
  - nuget restore Unosquare.Tubular.Lib.sln
  - npm install
before_script:
  - node -v
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm start > /dev/null &
  - npm run update-webdriver
  - sleep 1 # give server time to start
  - touch /home/travis/build/unosquare/tubular/Unosquare.Tubular/Javascript/tubular-bundle.js
  - touch /home/travis/build/unosquare/tubular/Unosquare.Tubular/Javascript/tubular-bundle.min.js
script:
  - xbuild /p:Configuration=Release Unosquare.Tubular.Lib.sln
  - npm run-script test-travis
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - node_modules/.bin/protractor e2e-tests/protractor.conf.js --browser=firefox
